# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CustomProps
                                 A QGIS plugin
 A QGIS plugin to inspect all custom properties of project layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-16
        copyright            : (C) 2025 by GIS Team by Eagleprojects
        email                : gis@eagleprojects.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CustomProps class from file CustomProps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .custom_props import CustomProps
    return CustomProps(iface)
